### ISSUE TITLE
onChange Event not working properly

### ISSUE THREAD

**Issue by h-assefi** [icemanbsi/searchable_dropdown#100]
In my code when ever onChange is called the value is the same even if other options get selected.
how to solve this problem ?

**Comment by ignaciotcrespo** [comment]
same issue here

**Comment by ignaciotcrespo** [comment]
@matheusfajardo created a PR (https://github.com/icemanbsi/searchable_dropdown/pull/84) to fix this, it is not merged yet. But you can use it in your project anyway

```
  searchable_dropdown:
      git:
        url: https://github.com/matheusfajardo/searchable_dropdown
        ref: master
```
